# Generated by Django 3.1.7 on 2021-04-05 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp1', '0002_auto_20210404_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Duration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 5, 4, 30, 1, 995239)),
        ),
    ]
