# Generated by Django 3.1.7 on 2021-04-06 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp1', '0007_auto_20210405_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Duration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 8, 46, 32, 858176)),
        ),
    ]
