# Generated by Django 3.1.7 on 2021-04-06 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp1', '0008_auto_20210406_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Duration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 8, 50, 17, 709360)),
        ),
    ]
