# Generated by Django 3.1.7 on 2021-04-06 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp1', '0009_auto_20210406_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Duration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 6, 12, 54, 36, 937655)),
        ),
    ]
