# Generated by Django 3.1.7 on 2021-04-07 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestApp1', '0010_auto_20210406_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecategory',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='coursecategory',
            name='title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='Duration',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 7, 6, 2, 59, 69671)),
        ),
    ]
